<?xml version="1.0" encoding="UTF-8"?>
<testng-results>
  <suite name="Galen Suite">
    <test name="Home page test">
      <class name="Home page test">
        <test-method status="FAIL" signature="Home page test" name="Home page test" duration-ms="5930000" started-at="2014-05-10T18:56:40Z" finished-at="2014-05-10T20:35:30Z" description="">
          <exception class="com.galenframework.components.report.FakeException">
            <message>FakeException: Some exception here</message>
            <full-stacktrace>com.galenframework.components.report.FakeException: Some exception here
                at net.mindengine.someclass.SomeClass.method1(SomeClass.java:4)
                at net.mindengine.someclass.SomeClass2.method2(SomeClass2.java:5)
                at net.mindengine.someclass.SomeClass3.method3(SomeClass3.java:6)
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
    <test name="Login page test">
      <class name="Login page test">
        <test-method status="PASS" signature="Login page test" name="Login page test" duration-ms="5930000" started-at="2014-05-10T18:56:40Z" finished-at="2014-05-10T20:35:30Z" description="">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>